# Generated by Django 4.1.2 on 2023-06-10 20:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('rut_admin', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nom_admin', models.CharField(max_length=20)),
                ('appater_admin', models.CharField(max_length=20)),
                ('apmater_admin', models.CharField(max_length=20)),
                ('email_admin', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator(), django.core.validators.MinLengthValidator(8)])),
                ('contrasena_admin', models.CharField(max_length=100)),
                ('fono_admin', models.IntegerField()),
                ('direccion_admin', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('rut_cli', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nom_cli', models.CharField(max_length=20)),
                ('appater_cli', models.CharField(max_length=20)),
                ('apmater_cli', models.CharField(max_length=20)),
                ('email_cli', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator(), django.core.validators.MinLengthValidator(8)])),
                ('contrasena_cli', models.CharField(max_length=100)),
                ('patente', models.CharField(max_length=6)),
                ('fono_cli', models.IntegerField()),
                ('direccion_cli', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='mecanico',
            fields=[
                ('rut_meca', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nom_meca', models.CharField(max_length=20)),
                ('appater_meca', models.CharField(max_length=20)),
                ('apmater_meca', models.CharField(max_length=20)),
                ('email_meca', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator(), django.core.validators.MinLengthValidator(8)])),
                ('contrasena_meca', models.CharField(max_length=100)),
                ('fono_meca', models.IntegerField()),
                ('direccion_meca', models.CharField(max_length=250)),
            ],
        ),
    ]
