<<<<<<< HEAD
# Generated by Django 4.1.2 on 2023-06-10 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rayo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='admin',
            new_name='administrador',
        ),
    ]
=======
# Generated by Django 4.1.2 on 2023-06-10 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rayo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='admin',
            new_name='administrador',
        ),
    ]
>>>>>>> 15b342c2a414660272a06bb0b89177a4567c1306
