<<<<<<< HEAD
# Generated by Django 4.1.2 on 2023-06-17 13:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rayo', '0002_rename_admin_administrador'),
    ]

    operations = [
        migrations.CreateModel(
            name='archivo',
            fields=[
                ('id_archivo', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('tipo_vehiculo', models.CharField(max_length=20)),
                ('fecha_ingreso', models.DateTimeField(default=django.utils.timezone.now)),
                ('tiempo_estimado', models.CharField(max_length=20)),
                ('diagnostico', models.CharField(max_length=20)),
                ('herramientas', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=20)),
                ('imagen', models.ImageField(null=True, upload_to='archivos')),
                ('rut_meca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rayo.mecanico')),
            ],
        ),
    ]
=======
# Generated by Django 4.1.2 on 2023-06-17 13:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rayo', '0002_rename_admin_administrador'),
    ]

    operations = [
        migrations.CreateModel(
            name='archivo',
            fields=[
                ('id_archivo', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('tipo_vehiculo', models.CharField(max_length=20)),
                ('fecha_ingreso', models.DateTimeField(default=django.utils.timezone.now)),
                ('tiempo_estimado', models.CharField(max_length=20)),
                ('diagnostico', models.CharField(max_length=20)),
                ('herramientas', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=20)),
                ('imagen', models.ImageField(null=True, upload_to='archivos')),
                ('rut_meca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rayo.mecanico')),
            ],
        ),
    ]
>>>>>>> 15b342c2a414660272a06bb0b89177a4567c1306
