# Generated by Django 4.1.2 on 2023-06-22 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rayo', '0003_archivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre_cat', models.CharField(max_length=20)),
                ('estado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='palabraClave',
            fields=[
                ('id_palabras', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('palabra', models.CharField(max_length=20)),
                ('categorias', models.ManyToManyField(to='rayo.categoria')),
            ],
        ),
    ]
