# Generated by Django 4.1.2 on 2023-07-06 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rayo', '0004_categoria_palabraclave'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='apmater_cli',
            new_name='aMaterno',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='appater_cli',
            new_name='aPaterno',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='contrasena_cli',
            new_name='contrasena',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='direccion_cli',
            new_name='direccion',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='email_cli',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='nom_cli',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='rut_cli',
            new_name='rut',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='fono_cli',
            new_name='telefono',
        ),
    ]
